In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\srinandhan\appdata\local\programs\python\python314\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\users\srinandhan\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\srinandhan\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\srinandhan\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\srinandhan\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
dataset=pd.read_csv('retail_sales_dataset.csv')
dataset

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [3]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [4]:
dataset.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

In [5]:
dataset.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [7]:
dataset.duplicated().sum()
dataset.T.duplicated().sum()

np.int64(0)

In [8]:
dataset.columns = dataset.columns.str.strip()
dataset['Customer ID']     = dataset['Customer ID'].str.strip().str.upper()
dataset['Gender']          = dataset['Gender'].str.strip().str.capitalize()
dataset['Product Category'] = dataset['Product Category'].str.strip().str.capitalize()
dataset['Gender'].value_counts()

Gender
Female    510
Male      490
Name: count, dtype: int64

In [9]:
dataset['Product Category'].value_counts()

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [10]:
dataset['Age'].value_counts(bins=5)

(54.8, 64.0]      216
(17.953, 27.2]    214
(45.6, 54.8]      208
(36.4, 45.6]      187
(27.2, 36.4]      175
Name: count, dtype: int64

In [11]:
dataset['Transaction ID'].is_unique
dataset['Customer ID'].is_unique

True

In [13]:
calculation = dataset['Quantity'] * dataset['Price per Unit']
contradiction = dataset[dataset['Total Amount'] != calculation]

len(contradiction)

0

In [14]:
dataset.to_csv('checked_retail_sales_dataset.csv', index=False)